# Generated by Django 3.2.19 on 2023-05-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_articles_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='caption',
            new_name='content',
        ),
    ]
